# Generated by Django 4.1.5 on 2023-02-11 20:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500, unique=True)),
                ('Description', models.TextField(default='New task')),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Last_Modified', models.DateTimeField(auto_now=True)),
                ('Completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Task',
            fields=[
                ('Sub_Task_Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=500, unique=True)),
                ('Description', models.TextField()),
                ('Date_created', models.DateTimeField(auto_now_add=True)),
                ('Due_date', models.DurationField(default=datetime.timedelta(days=7))),
                ('Last_modified', models.DateTimeField(auto_now=True)),
                ('Completed', models.BooleanField(default=False)),
                ('Reminder', models.BooleanField(default=True)),
                ('asigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.task')),
            ],
        ),
    ]
